
- name: Update apt packages
  remote_user: ubuntu
  apt:
    update_cache: yes

- name: Install Java package (Ubuntu/Debian)
  apt:
    name: openjdk-21-jdk
    state: present

- name: install the latest version of Apache Maven
  apt:
    name: maven
    state: latest