- name: Create target directory
  file:
    path: postgres
    state: directory
    mode: 0755


- name: copy sql maker file to remote
  copy:
    src: "../../../scripts/initSqlMaker.py"
    dest: "./postgres"
  when: test_case == 'store'

- name: copy hot record selector file to remote
  copy:
    src: "../../../scripts/hotRecordsSelector.py"
    dest: "./postgres"
  when: test_case == 'store'

- name: copy Dockerfile
  copy:
    src: "../../../Dockerfile"
    dest: "./postgres"

- name: install requirements
  pip:
    name: tqdm

- name: run initSqlMaker
  command: "python3 initSqlMaker.py"
  args:
    chdir: 'postgres'
  when: test_case == 'store'

- name: tpcc init
  include_tasks: tpcc_init.yml
  when: test_case == 'tpcc'


- name: build docker file
  command: 'docker build -t postgres_slw:init . --no-cache'
  args:
    chdir: 'postgres'

- name: run hot record selector
  command: "python3 hotRecordsSelector.py"
  args:
    chdir: 'postgres'
  when: test_case == 'store'