
- name: Copy benchbase-postgres.tgz
  copy:
    src: "../../../scripts/tpcc/benchbase-postgres.tgz"
    dest: "./postgres/benchbase-postgres.tgz"

- name: Extract benchbase-postgres.tgz
  ansible.builtin.unarchive:
    src: "./postgres/benchbase-postgres.tgz"
    dest: "./postgres"
    remote_src: yes

- name: Copy get_dump.sh script
  copy:
    src: "../../../scripts/tpcc/get_dump.sh"
    dest: "./postgres/get_dump.sh"
    mode: '0755'  # Make it executable

- name: Copy tpcc_config
  copy:
    src: "../../../scripts/tpcc/tpcc_config.xml"
    dest: "./postgres/tpcc_config.xml"

- name: Run get_dump.sh
  command: ./get_dump.sh {{tpcc_scale}}
  args:
    chdir: "postgres"
  become: yes

- name: Copy the output init_{{tpcc_scale}}.sql to init.sql
  copy:
    src: "./postgres/init_{{tpcc_scale}}.sql"
    dest: "./postgres/init.sql"
    remote_src: yes
