---
- name: restart postgres
  hosts: servers
  become: true

  vars:
    POSTGRES_VERSION: "12"
    PGDATA: "/data/postgres"
    BACKUP_DIR: "/data/postgres_backup"

  tasks:

    - name: Stop PostgreSQL service
      service:
        name: "postgresql@{{ POSTGRES_VERSION }}-main"
        state: stopped

    - name: Remove directory
      command: "rm -rf {{ PGDATA }}"
    - name: Load backup
      copy:
        src: "{{ BACKUP_DIR }}/"
        dest: "{{ PGDATA }}/"
        owner: postgres
        group: postgres
        mode: '0700'
        remote_src: yes

    - name: Start PostgreSQL service
      service:
        name: "postgresql@{{ POSTGRES_VERSION }}-main"
        state: started




